import './globals.css'
import { Inter, Montserrat } from 'next/font/google'

import { Providers } from '../components/Providers'

const monsterrat = Montserrat({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={monsterrat.className}>
        <Providers>
          {children}
        </Providers>
        </body>
    </html>
  )
}
